language: javascript
install: npm install node-sass
script:
  - env
  - node build/template_render
  - ./node_modules/.bin/node-sass scss/main.scss css/main.css
  - ./node_modules/.bin/node-sass scss/content_pages.scss css/content_pages.scss

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
